<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{98da3e34-4a61-4a8f-99e6-6cf9ea55f095}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	i			: DINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[i := i + 2;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>